name: main
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  invoke-sonarqube:
    name: Run SonarQube Analysis
    uses: ./.github/workflows/SonarQube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  invoke-coverage:
    name: Run Coverage
    uses: ./.github/workflows/Coverage.yml
  invoke-unittest:
    name: Run UnitTest
    uses: ./.github/workflows/UnitTest.yml